### PR TITLE
add support for emailing alarms

### PR DESCRIPTION
**Pull request by kmlucy**

### CODE REVIEW

**Comment by titpetric** [comment]
I'll merge this but I'd ask you to extend run.sh to provide config for ssmtp via env variables. Is this something you feel comfortable with?

**Comment by kmlucy** [comment]
I was working on having it copy a template to the folder if no user configuration was found:

https://github.com/kmlucy/netdata/commit/2858d2641460511a6fe6a7e9669b42e97efdd5bd

Do you think using env variables is the better way to go about it?

**Comment by titpetric** [comment]
Seems I cancelled run.sh at some point. Let me think about it.

Best,
Tit

**Comment by kmlucy** [comment]
Sure, will do.

**Comment by titpetric** [comment]
Hi,

sorry for a very long reply on my part. I have thought about it for a while, and I'm reasoning that we should re-implement run.sh, which would use env variables to create the ssmtp.conf. My reasoning is as follows:
1. I abandoned run.sh in favor of CMD because ENTRYPOINT doesn't evaluate env variables (https://github.com/docker/docker/issues/4783#issuecomment-77750475). I dropped run.sh just to bump netdata to pid 1 so it can take HUP/etc signals directly. With CMD this isn't the case and netdata doesn't end up on PID 1. Most of the mess came from this PR: https://github.com/titpetric/netdata/pull/9
2. We can consider tini to solve the PR issue instead of running run.sh - https://github.com/krallin/tini, the obvious requirement would be to have a script that runs before netdata for ssmtp config&other setup, and then run netdata, forwarding all the signals from pid 1.

Does this sound good to you, any comments?

Best,
Tit

**Comment by kmlucy** [comment]
Using tini seems like the best way to go about it. It seems like run.sh is needed for ssmtp configuration, one way or the other, and will make it a lot easier to add other features in the future.

**Comment by titpetric** [comment]
Due to an "unrelated" issue, I found out about the following:
http://wiki.bash-hackers.org/commands/builtin/exec

This makes it possible to use run.sh, and use `exec` to run netdata which will stay on PID 1.

**Comment by kmlucy** [comment]
That looks like it will work really well then. Was there anything else that you wanted to do in run.sh besides set up ssmtp?

**Comment by titpetric** [comment]
Nothing comes to mind currently. I'm adding run.sh as we speak, most likely this will be done in a few hrs.

**Comment by titpetric** [comment]
Ok, I added the "exec" part into run.sh. I also added support for running custom commands instead of netdata, which is what CMD enabled before.

I am verifying that netdata is indeed running on PID 1 now.

```
root@kraken:~/users/black/netdata# docker run -d titpetric/netdata
11b6d5a987dce353497593e19f15847d3cc3d38d25fd381c25b992da1544f932
root@kraken:~/users/black/netdata# docker exec -it big_almeida /bin/bash
root@11b6d5a987dc:/# ps auxw
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
netdata      1  1.5  0.1 836524  3608 ?        Ssl  10:54   0:00 /usr/sbin/netdata -D -s /host -p 19999
...
```

And that running custom commands against the netdata image works:

```
root@kraken:~/users/black/netdata# docker run -it --rm titpetric/netdata echo foo
Running custom cmd
foo
```

I'm pushing changes to my repo, feel free to modify run.sh to add generating the ssmtp config file from environment variables. I suggest 'SSMTP_' as the prefix for the supplied ENV vars.

**Comment by kmlucy** [comment]
I created a pull request for setting up ssmtp: #17 

I left in the option to set it up using a volume as well, for those like me that already have ssmtp set up in the base OS.

**Comment by titpetric** [comment]
Great works, thanks! Merged :)

**Comment by kmlucy** [comment]
Glad to help!

**Pull request merged**
