### PR TITLE
 Make SSMTP_USER and SSMTP_PASS environment variables optional

### PR DESCRIPTION
**Pull request by gersilex**
Compatibility for mail servers without authentication

Can be tested on Docker Hub: `gersilex/netdata:latest`

### CODE REVIEW

**Comment by titpetric** [comment]
Thanks, I actually have this in the pipeline, so I'll have to check if our versions match 🗡 :D

**Comment by gersilex** [comment]
Nice. I didn't see much activity here lately, so I just quick-fixed it, so that it works for me. Feel free to modify it in any way, as long as we can have the option to omit those two parameters in the ssmtp config file :+1:

**Comment by titpetric** [comment]
Good enough, my fix was more tailored to a specific client. Needs a bit of a revamp down the line :(

**Comment by titpetric** [comment]
I just realized that this wasn't necessary, ie, you could completely bypass ssmtp with `--add-host=mail:IP`. Adding the comment for posterity.

**Pull request merged**
