### PR TITLE
README: suggest to mount the whole host filesystem

### PR DESCRIPTION
**Pull request by jbq**
This allows to have visibility on all mounted disks

### CODE REVIEW

**Comment by jbq** [comment]
I'm unable to explain why, but this fix allows all mounted disks to be visible in netdata's Docker container.

**Comment by titpetric** [comment]
I'm not going to advocate bad practice, if you want to mount anything, it's up to your judgement.

**Comment by jbq** [comment]
Oh you're probably misunderstanding, it's only that Netdata doesn't see mounted filesystems unless I mount the whole host filesystem.  Shall I rather file an issue?

**Comment by titpetric** [comment]
You're going to get the same response on the issue. Netdata doesn't need anything else than proc/sys, and mounting the whole host is bad practice. If you need additional volumes, be more specific and don't mount the whole host. Also last time I checked, disks volumes like sda* etc. didn't need anything else except the proc filesystem, as this information is available from there:

```
# cat /sys/block/sda/stat
  839213    12766 15134362   635088   969552  3642608 64703232  6844672        0  1205760  7504520
```

https://www.kernel.org/doc/Documentation/block/stat.txt

If anything, you should mount explicit mounts into the container, if you want them to show up there, but I'm not aware of a local filesystem that wouldn't show up in the container. Try the official netdata/netdata image if the issue is solved there.

**Pull request closed without merging**
