### PR TITLE
update ssmtp config for run as root

### PR DESCRIPTION
**Pull request by kmlucy**

### CODE REVIEW

**Comment by kmlucy** [comment]
This is to update the ssmtp config for #18

**Comment by titpetric** [comment]
Sorry :) & Thanks.

**Comment by kmlucy** [comment]
No problem.

**Comment by titpetric** [comment]
I believe I'm going to do some changes to ssmtp configuration in regards to revaliases. The hardcoded netdata@SSMTP_HOSTNAME might not work for me. At least the run time hostname should be set (otherwise, I have no idea from which netdata/container instance the mail originated). Just pinging this thread because it will affect the FROM field

**Comment by titpetric** [comment]
@kmlucy why not just use $HOSTNAME (from the container?), why $SSMTP_HOSTNAME?

**Comment by kmlucy** [comment]
We could use $HOSTNAME. The original reason for a different variable was because unless you specifically pass a hostname to the container with `-h hostname`, the hostname is set to an random string. As long as we update the documentation to reflect that the hostname needs to be set, it should be fine.

**Comment by titpetric** [comment]
It is just as discriptive as "localhost", and it's possible to cut it off to the length that `docker ps` usually displays and not the full-length one. I'll think about it some more, thanks.

**Pull request merged**
