### PR TITLE
Reduce docker image layers and image size

### PR DESCRIPTION
**Pull request by solidnerd**
Thank you for your work. It works very well. 
I restructured your dockerfile to reduce the image layers and i could save some MB (~10MB). 

The next step would be an alpine image.

### CODE REVIEW

**Comment by titpetric** [comment]
Hi, thanks for the comments, the alpine issue is being worked on upstream. I'll add the rm -rf netdata.git, but I can't change the Dockerfile. ENV option persists to the built machine, but I will reformat it a bit for clarity. Thanks for your work.

**Comment by titpetric** [comment]
@SolidNerd very much thank you for some solid work. I added apt-get autoremove to clean up packages left by the build process, and removed all the build deps. From what I can see, the image size will go from about 370MB down to 160MB. I still have to test if everything works, but I am optimistic :) :+1: :100:

**Comment by solidnerd** [comment]
You are welcome !

**Comment by titpetric** [comment]
```
# docker images | grep netdata
titpetric/netdata            latest              f1165c796244        3 minutes ago       150.6 MB
netdata                      latest              5b88612231bd        5 minutes ago       165.8 MB
```

**Pull request closed without merging**
